package api.expenses.expenses.enums;

public enum EventType {
    MOVEMENT_FILE_ADDED,
    MOVEMENT_ADDED,
    MOVEMENT_DELETED,
    SERVICE_PAID,
    SERVICE_UPDATED,
    SERVICE_DELETED,
    GROUP_ADDED,
    GROUP_DELETED,
    INVITATION_CONFIRMED_REJECTED,
    INVITATION_ADDED,
    ACCOUNT_CREATED,
    ACCOUNT_LEFT
}
