spring:
  docker:
    compose:
      enabled: true
      file: docker-compose/docker-compose.yml

  datasource:
    url: jdbc:mysql://localhost:3306/expenses?createDatabaseIfNotExist=true&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true
    username: root
    password: helios
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: api-movements
    password: api-movements
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
