name: api-movements

services:

  mysql:
    image: mysql:latest
    container_name: api-movements-mysql
    environment:
      MYSQL_ROOT_PASSWORD: helios
      MYSQL_DATABASE: expenses
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api-movements

  rabbitmq:
    image: rabbitmq:management
    container_name: api-movements-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: localhost
      RABBITMQ_DEFAULT_PASS: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - api-movements

  redis:
    image: valkey/valkey:latest
    container_name: api-movements-redis
    ports:
      - "6379:6379"
    networks:
      - api-movements

networks:
  api-movements:
    driver: bridge

volumes:
  mysql_data:
