package api.m2.movements.enums;

public enum EventType {
    MOVEMENT_FILE_ADDED,
    MOVEMENT_ADDED,
    MOVEMENT_DELETED,
    SERVICE_PAID,
    SERVICE_UPDATED,
    SERVICE_DELETED,
    WORKSPACE_ADDED,
    WORKSPACE_DELETED,
    MEMBERSHIP_UPDATED,
    INVITATION_CONFIRMED_REJECTED,
    INVITATION_ADDED,
    WORKSPACE_CREATED,
    WORKSPACE_LEFT,
    CATEGORY_UPDATED
}
